# src/main/resources/application.properties

spring.datasource.url=jdbc:postgresql://localhost:5434/url_shortener-db
spring.datasource.username=admin
spring.datasource.password=admin123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs